### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EvertX** [dennisblokland/Curio#12]
Ver 1.0.3. crashlog: https://paste.dimdev.org/murugizuha.mccrash

**Comment by dennisblokland** [comment]
can you give me some information about when to crash happens?

**Comment by EvertX** [comment]
Sorry, yes. Having a bad day and seem to forget about half the things I do lately.
It happens when right-clicking (with an empty hand?) on an empty infusion table.

**Comment by dennisblokland** [comment]
do you have a link where I can download all the other mod used like a modpack or something because as only mod I can't replicate it.

**Comment by EvertX** [comment]
No, it's a custom pack I made myself. I'll do some tests this week when I have time to see if I can find the mod that does this.

**Comment by dennisblokland** [comment]
nvm i found out i do get an error but the client doesnt crash. so i should be able to fix it.

**Comment by dennisblokland** [comment]
thanks for downloading and reporting the issue. the latest version is now downloadable https://minecraft.curseforge.com/projects/curio/files/2668553
